app/assets/javascripts/controllers/CommonChatController.js

DEP-2511 : Changed Embedded DIV Id

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-embedded.scss

DEP-2511 : Fixed intro warn positioning

---

app/assets/javascripts/controllers/ReactiveChatController.js

DEP-2266: Fixed reactive popup button issue

DEP-2266: Fixed reactive popup button issue

---

app/assets/javascripts/services/Transcript.js
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2467: Accessibility feedback from live regions testing

---

app/assets/javascripts/controllers/CommonChatController.js
app/uk/gov/hmrc/digitalengagementplatformskin/config/AppConfig.scala
app/uk/gov/hmrc/digitalengagementplatformskin/config/ErrorHandler.scala
app/uk/gov/hmrc/digitalengagementplatformskin/controllers/HelloWorldController.scala
app/uk/gov/hmrc/digitalengagementplatformskin/views/ErrorTemplate.scala.html
app/uk/gov/hmrc/digitalengagementplatformskin/views/HelloWorldPage.scala.html
app/uk/gov/hmrc/digitalengagementplatformskin/views/Layout.scala.html
conf/application.conf

DEP-2436 : Look for fixed/anchored dev before embedded

---

app/assets/javascripts/chat-ui.js

DEP-2459: Turning on console message for any event

---

app/assets/javascripts/controllers/CommonChatController.js
app/uk/gov/hmrc/digitalengagementplatformskin/config/AppConfig.scala
app/uk/gov/hmrc/digitalengagementplatformskin/config/ErrorHandler.scala
app/uk/gov/hmrc/digitalengagementplatformskin/controllers/HelloWorldController.scala
app/uk/gov/hmrc/digitalengagementplatformskin/views/ErrorTemplate.scala.html
app/uk/gov/hmrc/digitalengagementplatformskin/views/HelloWorldPage.scala.html
app/uk/gov/hmrc/digitalengagementplatformskin/views/Layout.scala.html
conf/application.conf
test/uk/gov/hmrc/digitalengagementplatformskin/controllers/HelloWorldControllerSpec.scala

DEP-2436 : Target the correct div to inject iframe for popup

---

app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP:2467: Live region for chat container

---

app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2467: Fixed content and css

---

app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2467: Added log role

---

app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2467 : Reverted for Testing on NVDA chrome

---

app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2524: Decoded message string for opener script

---

app/assets/javascripts/services/Transcript.js
app/assets/stylesheets/transcript-agent.scss
app/assets/stylesheets/transcript-customer.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2602: Changed scroll to fit in screen

---

app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js

DEP-2479 : Fix typo

---

README.md
app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/PostChatSurveyDigitalAssistantService.js
app/assets/javascripts/services/PostChatSurveyWebchatService.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js

DEP-2478: PCS for DA only questions and answers

---

app/assets/javascripts/utils/ChatContainer.js

DEP-2571 : Add hrefs to jump links

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js

DEP-2480 : Add Post Chat Survey logic

---

README.md

DEP-UpdateReadme : Added steps to obtain code coverage

---

app/assets/javascripts/services/Transcript.js
app/assets/stylesheets/custom.css
app/assets/stylesheets/transcript-agent.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

added focus and opacity

---

app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js

Improved latest accessibility findings

---

app/assets/javascripts/chat-ui.js
app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js
app/assets/javascripts/utils/ChatContainer.js
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-embedded.scss
app/assets/stylesheets/chat-ui-popup.scss
app/assets/stylesheets/transcript-agent.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

DEP-2757: Adding print functionality

---

app/assets/javascripts/services/Transcript.js

DEP-2790 : Fix Repeated announcements

---

app/assets/javascripts/services/Transcript.js
app/assets/stylesheets/chat-ui-embedded.scss
app/assets/stylesheets/transcript-agent.scss

DEP-2575 : Fix font/timestamp/backdround colour on print dialogue

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-2758 : Fix turn notification sound off

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-2758 : Fix sound notification on mobile devices

---

app/assets/javascripts/utils/ChatContainer.js
app/assets/javascripts/views/postChatSurvey/PostPCSPage.js

DEP-2823 : Remove print/sound buttons on end chat pages (and dead space)

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/utils/ChatContainer.js
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-2758 : Test to see if this implementation works on iphone

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/utils/ChatContainer.js
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-2758: Revert code that tried to get IOS working

---

app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js

Link to AT PR : https://github.com/hmrc/digital-engagement-platform-journey-tests/pull/84

[DEP-2810][PR]:Feedback form - textarea missing label

---

app/assets/javascripts/services/Transcript.js

[DEP-2804][PR]:Focus on virtual assistant DAv3

---

app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js

Link to AT PR : https://github.com/hmrc/digital-engagement-platform-journey-tests/pull/85

[DEP-2810][PR]:Worked on Review comments

---

app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

[DEP-2805][PR]:Fix for heading hierarchy for different messages

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js

DEP-2914 : Update adviser when user closes chat (before PCS)

---

app/assets/javascripts/NuanceMessageState.js
app/assets/javascripts/NuanceMessageType.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js

DEP-2822 Enable screen reader to read "Agent is typing" on DA message

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js
app/assets/javascripts/utils/ChatContainer.js

DEP-2804 : Use event listener to capture VA link click and send focus to new incoming DA message

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js
app/assets/javascripts/utils/ChatContainer.js

DEP-2804 : Fix failing tests

---

app/assets/stylesheets/chat-ui-embedded.scss

DEP-3056 : Fix Overlapping controls on smaller / zoom screens

---

app/assets/javascripts/utils/ChatContainer.js
app/assets/javascripts/views/EndChatPopup.js
app/assets/stylesheets/end-chat-popup.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/views/EndChatPopup.spec.js

DEP-3057 : Fix End chat dialog for screen readers

---

app/assets/javascripts/controllers/CommonChatController.js

DEP-3097: Remove skin heading buttons when PCS is not used

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/utils/ChatContainer.js

DEP-3097 : Only remove skin heading buttons if they are available

---

app/assets/javascripts/controllers/CommonChatController.js

DEP-3107: Send correct automaton survey id and name to nuance

---

app/assets/javascripts/controllers/CommonChatController.js

DEP-3023: Add dav3 to deskpro referer urls when dav3 is shown

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-3028: Call end chat model on end chat link click

---

app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/utils/ChatContainer.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-3028: refactor code and ensure focus remains on end chat modal

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/utils/ChatContainer.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-3028: Call endchat popup on endchat and give feedback link click

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js

Link to AT PR : https://github.com/hmrc/digital-engagement-platform-journey-tests/pull/89
-  [x]  If relevant, I've added links to associated PRs

[DE{-3169][PR]:DAV3 DA PCS chatbot update

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js

[DEP-3169][PR]:Removed word today

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/utils/ChatContainer.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js

DEP-2766: send start/stop typing activity message to nuance

---

project/AppDependencies.scala

[DEP-3048][PR]:Library upgrades

---

app/assets/stylesheets/bubble.scss
app/assets/stylesheets/chat-ui-embedded.scss
app/assets/stylesheets/transcript-agent.scss
app/assets/stylesheets/transcript-customer.scss

DEP-3096 Updated css to allow UI to resize with text size

---

app/assets/stylesheets/chat-ui-embedded.scss

DEP-3096a Fix height issue

---

app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js

Fix styling on both DAV3 PCS pages

---

conf/application.conf

DEP : Remove assets-frontend config

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-2634 ; chat denied message should come from nuance portal

---

app/assets/javascripts/chat-ui.js
app/assets/javascripts/controllers/CommonChatController.js
app/assets/stylesheets/chat-ui-embedded.scss

DEP-3384 : addressed comments and todos

---

app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js

DEP-3413 : Update embedded form send button text

---

gulpfile.js
package.json

DEP-2843 : Uglify bundled js file

---

app/assets/javascripts/views/postChatSurvey/PostPCSPage.js
package.json

DEP-3157: made chat ended text a H2

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DEP 3452 - update dependencies 

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/services/PostChatSurveyDigitalAssistantService.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js
build.sbt
conf/application-json-logger.xml
project/JavaScriptBuild.scala
project/build.properties
project/plugins.sbt
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyWebchatService.spec.js

Dep 3464: Post Chat Survey Update

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/utils/PrintUtils.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/utils/PrintUtils.spec.js

Fix issue where chat transcript was not printed correctly from the post chat survey.

Dep 3909 - Post Chat Survey Print Functionality

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyWebchatService.spec.js

Amend post chat survey contents for digital assistant and webchat PCS

Dep 3889 - update PCS for both surveys

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/ChatStates.spec.js

DEP-4096 use isAgentMsg property on message to support Mix agent messages

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStatesMix.spec.js

DEP-4182 Check any extra NINA functionalities within the automation.request still function

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStatesMix.spec.js

Dep 4182 - Check any extra NINA functionalities within the automation.request still function

---

app/assets/javascripts/services/Transcript.js
app/assets/javascripts/utils/ChatContainer.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/utils/ChatContainer.spec.js

DEP-MIX-FIXES 

---

app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js

DEP-4129 Mix bug - character code display

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

DEP-4098 add youtube video message logic

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/utils/ChatContainer.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/utils/ChatContainer.spec.js

DEP 4206 - stop activity messages being sent on every keypress

---

package.json
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStatesMix.spec.js

DEP-3976: Updating JS libraries

---

app/assets/javascripts/services/ChatStates.js
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

DEP-4228: Added code to allow full screen mode on videos

---

app/assets/javascripts/services/ChatStates.js
app/assets/stylesheets/transcript-agent.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

DEP-4443 Combined video message into a single chat bubble.

---

app/assets/javascripts/chat-ui.js
app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/hmrcChatSkin.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/chat-ui.spec.js

Dep 4273 Test chat-ui.js

---

app/assets/javascripts/controllers/CommonChatController.js

DEP-4047 Added method to retrieve feature switches.

---

app/assets/stylesheets/transcript-agent.scss

DEP-4514 removed horizontal line on agent message bubble

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/utils/ChatContainerEventListener.spec.js

DEP-4453 fixed pop up sound button functionality

---

app/assets/media/close-white.svg
app/assets/media/minimise-white.svg
app/assets/stylesheets/chat-ui-popup.scss

-  [x]  If relevant, I've added links to associated PRs

header blue and text white

---

app/assets/javascripts/services/ChatStates.js

-  [x]  If relevant, I've added links to associated PRs

testing hotfix

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/stylesheets/chat-ui-popup.scss
conf/application.conf
project/plugins.sbt

Dep 5185 pcs fix

---

app/assets/stylesheets/chat-ui-popup.scss

resized text input and send button

---

app/assets/stylesheets/chat-ui-popup.scss
conf/application.conf
project/plugins.sbt

DEP-2379 Fullscreen landscape popup fix.

---

app/assets/javascripts/controllers/CommonChatController.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js

-  [x]  If relevant, I've added links to associated PRs

DEP-5411: Targeting new popup ID in the chat-skin and updating related tests

---

app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.js
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.js

DEP-5184 updated PCS content

---

app/assets/javascripts/services/Transcript.js
app/assets/stylesheets/chat-ui-common.scss

DEP-5192: Reduce space between chat bubbles in print preview (popup/embedded)

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-popup.scss

DEP-5193: Adding accessibility link to the popup with hardcoded URL

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-popup.scss

DEP-5193: FIxed accessibility statement showing in print preview

---

app/assets/stylesheets/transcript-agent.scss
app/assets/stylesheets/transcript-customer.scss

DEP-5237: Fix message bubbles cutting off at page breaks in print preview

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-popup.scss

DEP-5234: Fixed layout shift on popup message box

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-common.scss
app/assets/stylesheets/chat-ui-popup.scss

made styling changes

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-popup.scss

improved minimised popup

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

added URL for embedded videos

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

added a title to the iframe

---

app/assets/javascripts/services/ChatStates.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

added accessibility for embedded videos

---

app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

DEP-4822 message time stamp added to message headings

---

app/assets/javascripts/controllers/CommonChatController.js

DEP-5601 Changed automated meessage detection method to classname.

---

app/assets/stylesheets/chat-ui-popup.scss

DEP-5641 remove border from popup pcs css

---

app/assets/javascripts/services/ChatStates.js

DEP-5638 suppressed transfer message in preprod

---

app/assets/stylesheets/chat-ui-popup.scss
project/plugins.sbt

changed css to sort out video messages

---

app/assets/stylesheets/chat-ui-popup.scss
project/plugins.sbt

fixing the accessibility statement to the bottom

---

app/assets/javascripts/views/popup/PopupContainerHtml.js

DEP-5465 made accessibility statement url dynamic

---

app/assets/javascripts/views/popup/PopupContainerHtml.js

removed console log

---

app/assets/javascripts/services/Transcript.js

DEP-5740 Fix issues with regular links in quick reply messages

---

app/assets/javascripts/utils/ChatContainer.js
app/assets/javascripts/views/popup/PopupContainerHtml.js

tabindex added to close and minimise

---

app/assets/javascripts/services/ChatStates.js
conf/application.conf
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

removed YouTube URL

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-common.scss
app/assets/stylesheets/chat-ui-popup.scss

fixed send when in reflow

---

app/assets/javascripts/chat-ui.js
app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/utils/ClickToChatButtons.js

DEP-c2c-fix Fixed feedback survey for reactive popup

---

app/assets/stylesheets/chat-ui-popup.scss

DEP-css-fix Changed div styling to only affect the popup container.

---

app/assets/stylesheets/chat-ui-common.scss

DEP-5321 Fixed spacing issues on reload and adding more consistent spacing

---

app/assets/javascripts/controllers/CommonChatController.js

added focus to the minimise button when restoring chat

---

app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js

changed label

---

app/assets/javascripts/views/EndChatPopup.js
project/AppDependencies.scala

DEP-5805 Updated libraries and added missing class to survey links.

---

app/assets/javascripts/controllers/CommonChatController.js

DEP-5820-2 minimise fix

---

app/assets/javascripts/views/EndChatPopup.js
app/assets/stylesheets/end-chat-popup.scss

changed heading to h2

---

app/assets/javascripts/utils/ChatContainer.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/utils/ChatContainer.spec.js

DEP-focus_fix fix to text area & input tab index

---

app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js

DEP-5801 Removed image role from image tags.

---

app/uk/gov/hmrc/digitalengagementplatformskin/config/ErrorHandler.scala
app/uk/gov/hmrc/digitalengagementplatformskin/views/ErrorTemplate.scala.html
project/plugins.sbt

DEP-3974 replace error handler missing method

---

app/assets/stylesheets/transcript-agent.scss
app/assets/stylesheets/transcript-customer.scss

DEP-2882 scss overflow-wrap fix

---

app/assets/javascripts/views/postChatSurvey/CommonPostChatSurvey.js
app/assets/javascripts/views/postChatSurvey/PostPCSPage.js

DEP-userAgentError fix

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/popup/PopupContainerHtml.js

added in aria-state to hamburger button

---

app/assets/stylesheets/end-chat-popup.scss

resolved end chat popup size

---

app/assets/javascripts/views/popup/PopupContainerHtml.js
app/assets/stylesheets/chat-ui-popup.scss

changed sizes and added arrow

---

app/assets/javascripts/chat-ui.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/chat-ui.spec.js

changed the way agent id is assigned

---

app/assets/javascripts/views/postChatSurvey/PostPCSPage.js
app/assets/stylesheets/chat-ui-embedded.scss
app/assets/stylesheets/chat-ui-popup.scss

DEP-6218-2 fixed link styling

---

app/assets/javascripts/services/ChatStates.js

DEP-6155 added default system messages when blank

---

app/assets/stylesheets/chat-ui-popup.scss

DEP-6212-2 size button focus styling

---

app/assets/javascripts/controllers/CommonChatController.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js

DEP-6098 added error message for duplicated tabs/windows

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/controllers/ReactiveChatController.js
app/assets/javascripts/services/ChatStates.js
app/assets/javascripts/services/Transcript.js
app/assets/javascripts/utils/Messages.js
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.js
app/assets/javascripts/views/popup/PopupContainerHtml.js

Created the Messages.js file within the utils folder. I have checked for messages within the skin and placed them in the Messages.js file. I have then imported the Messages.js file into the relevant files so that the messages can be used. This makes the messages more reusable and ensures they are all in one place.

Messages.js created and messages added.

---

app/assets/stylesheets/chat-ui-common.scss
conf/logback.xml
project/build.properties
project/plugins.sbt

changed spacing between quick replies

---

app/assets/javascripts/utils/ClickToChatButtons.js

Removed the img and div elements containing the link to the old crown/

---

app/assets/javascripts/views/postChatSurvey/CommonPostChatSurvey.js
conf/logback.xml
package-lock.json
package.json
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/setup.js

removal of jquery

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/postChatSurvey/CommonPostChatSurvey.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js

removed the init all and replicated the js for hidden questions

---

app/assets/javascripts/controllers/CommonChatController.js

changed the accessibility link

---

app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.ts
app/assets/javascripts/views/postChatSurvey/PostPCSPage.ts
app/assets/stylesheets/chat-ui-embedded.scss
app/assets/stylesheets/chat-ui-popup.scss

DEP-accessibility fixed link styling

---

app/assets/javascripts/views/postChatSurvey/PostPCSPage.ts
app/assets/stylesheets/chat-ui-popup.scss

fix print link styling

---

app/assets/javascripts/controllers/CommonChatController.js
app/assets/javascripts/views/popup/PopupContainerHtml.ts
app/assets/javascripts/views/postChatSurvey/CommonPostChatSurvey.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.ts
app/assets/stylesheets/chat-ui-common.scss
app/assets/stylesheets/chat-ui-embedded.scss
app/assets/stylesheets/chat-ui-popup.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/views/PostChatSurvey/CommonPostChatSurvey.spec.js

error messages and skip button

---

app/assets/stylesheets/chat-ui-common.scss

resolved reflow issue with send button

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/utils/ChatContainer.ts

enabled closing of the hamburger menu on other actions

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/controllers/ProactiveChatController.ts
app/assets/javascripts/services/ChatStates.ts
app/assets/javascripts/services/Transcript.ts
tsconfig.json

Commenting out the unused parameters was causing issues so I have put them back in and relaxed the TS config rules. Without doing this, VSCode gives us a warning and the PR builder fails.

DEP-6477-fix

---

app/assets/javascripts/utils/ChatContainer.ts

disabled send button when box is empty

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/utils/ChatContainer.ts
app/assets/javascripts/views/embedded/EmbeddedContainerHtml.ts
app/assets/javascripts/views/popup/PopupContainerHtml.ts

DEP-2969-rework

---

app/assets/javascripts/chat-ui.ts
app/assets/javascripts/controllers/ReactiveChatController.ts
app/assets/javascripts/services/ChatStates.ts
app/assets/javascripts/utils/Messages.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/chat-ui.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/ReactiveChatController.spec.js

Created a new branch to fix the merge conflicts for DEP-6534

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.ts
app/assets/stylesheets/chat-ui-common.scss

changed error messages and questions on survey

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.ts
app/assets/stylesheets/chat-ui-common.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyWebchatService.spec.js

Dep 6687 missed questions

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyWebchatService.spec.js

changed survey wording

---

app/assets/javascripts/controllers/CommonChatController.ts
project/plugins.sbt

link to new statement

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/utils/ClickToChatButton.ts
app/assets/javascripts/utils/ClickToChatButtons.ts
app/assets/javascripts/views/popup/PopupContainerHtml.ts

Removed the box from saying you are speaking to a computer on C2C.

---

app/assets/javascripts/chat-ui.ts
app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/controllers/ProactiveChatController.ts
app/assets/javascripts/controllers/ReactiveChatController.ts
app/assets/javascripts/types.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/ReactiveChatController.spec.js

DEP-6691-6692

---

app/assets/javascripts/controllers/CommonChatController.ts

added env param for AS

---

app/assets/javascripts/controllers/CommonChatController.ts

enable auto engagement on reactive chats

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/utils/ChatContainer.ts

corrected the way the menu works

---

app/assets/javascripts/utils/ChatContainer.ts

menu dropdown closes after tabbing off it

---

app/assets/javascripts/controllers/CommonChatController.ts

focus on maximise when minimise is clicked

---

app/assets/javascripts/controllers/CommonChatController.ts

shifted focus to input on popup opening

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/utils/ChatContainer.ts

resolved menu toggle

---

app/assets/javascripts/controllers/CommonChatController.ts

focus on text box

---

app/assets/javascripts/controllers/CommonChatController.ts

moved focus call

---

app/assets/stylesheets/chat-ui-popup.scss

Removing govuk font to remove console errors

---

app/assets/javascripts/controllers/CommonChatController.ts

resolved url issues for AS

---

test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/Transcript.spec.js

Testing: Added two unit tests for the change of content around agent hmrcda exits chat.

---

app/assets/javascripts/services/ChatStates.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

reverting keepAlive function

---

app/assets/javascripts/controllers/CommonChatController.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/CommonChatController.spec.js

C2C Phase 2: SA IVR

---

app/assets/javascripts/views/EndChatPopup.ts

changed end modal text

---

app/assets/javascripts/utils/ClickToChatButton.ts
app/assets/javascripts/utils/ClickToChatButtons.ts
app/assets/javascripts/utils/Messages.ts
app/assets/stylesheets/c2cbutton.scss
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/controllers/ReactiveChatController.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/utils/ClickToChatButtons.spec.js

DEP-7043: Change to functionality and styling of the fixed C2C

---

app/assets/stylesheets/chat-ui-popup.scss
app/assets/stylesheets/end-chat-popup.scss

chnaged colours to black

---

app/assets/stylesheets/chat-ui-popup.scss

changed colours for hover

---

app/assets/stylesheets/chat-ui-popup.scss

DEP-7034 setting background color in dropdown content button

---

app/assets/javascripts/services/ChatStates.ts
app/assets/javascripts/services/Transcript.ts
app/assets/javascripts/utils/Messages.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/chat-states/ChatStates.spec.js

changed system messages

---

app/assets/javascripts/controllers/CommonChatController.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyDigitalAssistant.ts
app/assets/javascripts/views/postChatSurvey/PostChatSurveyWebchat.ts
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyDigitalAssistantService.spec.js
test/uk/gov/hmrc/digitalengagementplatformskin/javascripts/services/PostChatSurveyWebchatService.spec.js

updated survey wording

---

build.sbt
conf/application.conf

DEP-7122: Updated HttpClient to V2Module and removed JCenter.

---

app/assets/javascripts/chat-ui.ts

removed auto engage from TT

---

build.sbt
package-lock.json
package.json
project/AppDependencies.scala

23 vulnerabilities are now fixed

Upgrade to Scala 3
